// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmzdecejydvcjwtzfinz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtemRlY2VqeWR2Y2p3dHpmaW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDYzNzIsImV4cCI6MjA2NzYyMjM3Mn0.WADpdgCkIiStLJ4c5FJ5LLkdrdYZgUjqjvjj54j01AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});